const majorTimeZones = [
  { label: "(UTC-12:00) International Date Line West", value: "Etc/GMT+12" },
  { label: "(UTC-11:00) Coordinated Universal Time-11", value: "Etc/GMT+11" },
  { label: "(UTC-10:00) Hawaii", value: "Pacific/Honolulu" },
  { label: "(UTC-09:00) Alaska", value: "America/Anchorage" },
  { label: "(UTC-08:00) Pacific Time (US & Canada)", value: "America/Los_Angeles" },
  { label: "(UTC-07:00) Mountain Time (US & Canada)", value: "America/Denver" },
  { label: "(UTC-06:00) Central Time (US & Canada)", value: "America/Chicago" },
  { label: "(UTC-05:00) Eastern Time (US & Canada)", value: "America/New_York" },
  { label: "(UTC-04:00) Atlantic Time (Canada)", value: "America/Halifax" },
  { label: "(UTC-03:00) Buenos Aires", value: "America/Argentina/Buenos_Aires" },
  { label: "(UTC-02:00) Mid-Atlantic - Old", value: "Etc/GMT+2" },
  { label: "(UTC-01:00) Azores", value: "Atlantic/Azores" },
  { label: "(UTC+00:00) Greenwich Mean Time : Dublin, Edinburgh, Lisbon, London", value: "Europe/London" },
  { label: "(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna", value: "Europe/Berlin" },
  { label: "(UTC+02:00) Athens, Bucharest", value: "Europe/Athens" },
  { label: "(UTC+03:00) Moscow, St. Petersburg, Volgograd", value: "Europe/Moscow" },
  { label: "(UTC+04:00) Abu Dhabi, Muscat", value: "Asia/Dubai" },
  { label: "(UTC+05:00) Islamabad, Karachi", value: "Asia/Karachi" },
  { label: "(UTC+06:00) Astana", value: "Asia/Almaty" },
  { label: "(UTC+07:00) Bangkok, Hanoi, Jakarta", value: "Asia/Bangkok" },
  { label: "(UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi", value: "Asia/Shanghai" },
  { label: "(UTC+09:00) Osaka, Sapporo, Tokyo", value: "Asia/Tokyo" },
  { label: "(UTC+10:00) Brisbane", value: "Australia/Brisbane" },
  { label: "(UTC+11:00) Solomon Is., New Caledonia", value: "Pacific/Noumea" },
  { label: "(UTC+12:00) Auckland, Wellington", value: "Pacific/Auckland" },
];

export default majorTimeZones;
